// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using basics.Data;

#nullable disable

namespace basics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251209192013_AddSeatingPlanStatus")]
    partial class AddSeatingPlanStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("basics.Areas.Admin.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KoltukDuzeni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SalonAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SalonKapasitesi")
                        .HasColumnType("int");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Salonlar");
                });

            modelBuilder.Entity("basics.Areas.Admin.Models.SeatingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 12, 9, 19, 20, 11, 668, DateTimeKind.Utc).AddTicks(5309));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<string>("PlanAdi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SalonAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 12, 9, 19, 20, 11, 668, DateTimeKind.Utc).AddTicks(5813));

                    b.HasKey("Id");

                    b.ToTable("SeatingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
