// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using basics.Data;

#nullable disable

namespace basics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251210131225_AddEtkinlikSistemi")]
    partial class AddEtkinlikSistemi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("basics.Areas.Admin.Models.Etkinlik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("BiletFiyati")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("EtkinlikAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<bool>("SatisAktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("TarihSaat")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SalonId");

                    b.ToTable("Etkinlikler");
                });

            modelBuilder.Entity("basics.Areas.Admin.Models.EtkinlikKoltuk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Blok")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DoluMu")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EtkinlikId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("KoltukNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Numara")
                        .HasColumnType("int");

                    b.Property<string>("Sira")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EtkinlikId");

                    b.ToTable("EtkinlikKoltuklari");
                });

            modelBuilder.Entity("basics.Areas.Admin.Models.Salon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KoltukDuzeni")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SalonAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SalonKapasitesi")
                        .HasColumnType("int");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Salonlar");
                });

            modelBuilder.Entity("basics.Areas.Admin.Models.SeatingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 12, 10, 13, 12, 24, 19, DateTimeKind.Utc).AddTicks(6460));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<string>("PlanAdi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SalonAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 12, 10, 13, 12, 24, 19, DateTimeKind.Utc).AddTicks(6954));

                    b.HasKey("Id");

                    b.ToTable("SeatingPlans");
                });

            modelBuilder.Entity("basics.Areas.Admin.Models.Etkinlik", b =>
                {
                    b.HasOne("basics.Areas.Admin.Models.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("basics.Areas.Admin.Models.EtkinlikKoltuk", b =>
                {
                    b.HasOne("basics.Areas.Admin.Models.Etkinlik", "Etkinlik")
                        .WithMany()
                        .HasForeignKey("EtkinlikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etkinlik");
                });
#pragma warning restore 612, 618
        }
    }
}
